DELIMITER //
CREATE FUNCTION to_date(in_date varchar(9), format varchar(9))
 RETURNS VARCHAR(8)
 BEGIN
  DECLARE D_DAY VARCHAR(2);
  DECLARE D_MONTH VARCHAR(3);
  DECLARE D_YEAR VARCHAR(4);
  DECLARE TWOD_YEAR VARCHAR(2);
  DECLARE CENTURY VARCHAR(4);
  SET D_DAY = substr(in_date,1,2);
  SET D_MONTH = substr(in_date,4,3);
  SET D_YEAR = substr(in_date,8,2);
  IF D_MONTH = 'JAN' THEN SET D_MONTH='01';
  ELSEIF D_MONTH = 'FEB' THEN SET D_MONTH='02';
  ELSEIF D_MONTH = 'MAR' THEN SET D_MONTH='03';
  ELSEIF D_MONTH = 'APR' THEN SET D_MONTH='04';
  ELSEIF D_MONTH = 'MAY' THEN SET D_MONTH='05';
  ELSEIF D_MONTH = 'JUN' THEN SET D_MONTH='06';
  ELSEIF D_MONTH = 'JUL' THEN SET D_MONTH='07';
  ELSEIF D_MONTH = 'AUG' THEN SET D_MONTH='08';
  ELSEIF D_MONTH = 'SEP' THEN SET D_MONTH='09';
  ELSEIF D_MONTH = 'OCT' THEN SET D_MONTH='10';
  ELSEIF D_MONTH = 'NOV' THEN SET D_MONTH='11';
  ELSEIF D_MONTH = 'DEC' THEN SET D_MONTH='12';
  END IF;
  SET TWOD_YEAR = substr(YEAR(CURDATE()),3,2);
  SET CENTURY = YEAR(CURDATE()) - TWOD_YEAR;
  IF TWOD_YEAR >= 0 AND TWOD_YEAR <= 49 THEN
   IF D_YEAR >= 0 AND D_YEAR <= 49 THEN
    SET D_YEAR = CENTURY + D_YEAR;
   ELSE
    SET D_YEAR = CENTURY - 100 + D_YEAR;
   END IF;
  ELSE
   IF D_YEAR >= 0 AND D_YEAR <= 49 THEN
    SET D_YEAR = CENTURY + 100 + D_YEAR;
   ELSE
    SET D_YEAR = CENTURY + D_YEAR;
   END IF;
  END IF;
  return CONCAT(D_YEAR,D_MONTH,D_DAY);
 END //
DELIMITER ;
